name: Scheduled run

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */2 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install
    - name: Run script
      env:
        RECUETIME_API_KEY: '${{ secrets.RECUETIME_API_KEY }}'
        TWITTER_USERNAME: '${{ secrets.TWITTER_USERNAME }}'
        TWITTER_CONSUMER_KEY: '${{ secrets.TWITTER_CONSUMER_KEY }}'
        TWITTER_CONSUMER_SECRET: '${{ secrets.TWITTER_CONSUMER_SECRET }}'
        TWITTER_ACCESS_TOKEN_KEY: '${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}'
        TWITTER_ACCESS_TOKEN_SECRET: '${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}'
        TELEGRAM_API_KEY: '${{ secrets.TELEGRAM_API_KEY }}'
        TELEGRAM_CHAT_ID: '${{ secrets.TELEGRAM_CHAT_ID }}'
      run: node index.js
